### ISSUE TITLE
Lot of improvements + Android support

### ISSUE THREAD

**Issue by amerkoleci** [chrisdunelm/DotNetAnywhere#5]
I've pushed changes to DNA, please see my fork:
https://github.com/amerkoleci/DotNetAnywhere

More .NET 4.0 support.
Improved generics and heap support.
Android support.
Multi dimensional array.
PInvoke on windows with better function invocation.
Improved reflection.
Clear code and fix some op code issues.
Resx file support.
Improved Linq and add support for nUnit.

Could anybody take care of my changes and maybe revive this project?
I have some null references once GarbageCollect gets called, could take look please?

**Comment by bencz** [comment]
You have the sources yet ?

**Comment by chrisdunelm** [comment]
This project is entirely inactive. I won't be doing any more work on it.
