### ISSUE TITLE
Ray Trace Benchmark Bad Mem Errors

### ISSUE THREAD

**Issue by zezba9000** [chrisdunelm/DotNetAnywhere#6]
Was porting over my C# benchmark: https://github.com/zezba9000/RayTraceBenchmark
But I run into bad memory access errors that i'm pretty sure are coming from the heap.

I was unable to find the location of the issue in the C code.  I can post up the code that fails if anyone still cares about this project anymore?

**Comment by chrisdunelm** [comment]
Sadly, no-one cares about this project any more :(

**Comment by mattwarren** [comment]
> Sadly, no-one cares about this project any more :(

I wouldn't say no-one cares ;-) have you seen [Blazor](https://github.com/SteveSanderson/Blazor) and [Blazor Brings .NET Back to the Browser](https://www.infoq.com/news/2017/07/Blazor)?

**Comment by zezba9000** [comment]
Mono is already starting to run in WASM. Mono also already runs in PNaCl and Bridge.NET transpiles C# in JS.

DotNetAnywhere is a good notion like Unity3D's IL2CPP that always .NET to run on any CPU the Mono/.NET JIT doesn't run on. Whats needed is a CoreRT to C98 target to create an open source version of IL2CPP that runs anywhere.

**Comment by chrisdunelm** [comment]
@mattwarren I had no idea! How amusing to see it still alive and running in a browser :) Thanks for letting me know.

@zezba9000 Yes something like CoreRT -> C or even CoreRT -> JS (similar I suppose to [scala.js](https://www.scala-js.org/) for Scala) would be great. Years ago I wrote [DotNetWebToolkit](https://github.com/chrisdunelm/DotNetWebToolkit), an IL -> JS transcoder which worked, but was never completed.

**Comment by mattwarren** [comment]
> I had no idea! How amusing to see it still alive and running in a browser :) Thanks for letting me know.

No problem, BTW I liked your project so much that I did a write-up on it, [DotNetAnywhere: An Alternative .NET Runtime](http://mattwarren.org/2017/10/19/DotNetAnywhere-an-Alternative-.NET-Runtime/) (I hope there's not too many errors!!)
