### ISSUE TITLE
What about tailcalls?

### ISSUE THREAD

**Issue by dsyme** [chrisdunelm/DotNetAnywhere#8]
The inevitable F# questions :)  
1. Are tailcalls supported? 
2. If not, is the tailcall prefix at least ignored? (The majority of F# code can still execute correctly when the tailcall prefix is ignored, though ideally it should be supported)

Thanks!

**Comment by chrisdunelm** [comment]
1. Sadly not
2. Probably not

This was all developed quite some time ago, so I can't exactly remember if I ever came across tailcalls.
But I only implemented exactly what was required to execute the things I tested it with, and I only ever used C# code during testing. I expect I never came across a tailcall at all, so I expect it's totally unhandled.

I don't anticipate developing this any further, so it will probably languish in this unloved tailcallless state forevermore...

**Comment by dsyme** [comment]
Ok, thanks for taking the time to close this out!

**Comment by chrisdunelm** [comment]
@dsyme Since closing this I've since discovered that this code lives on in [Blazor](https://github.com/SteveSanderson/Blazor/), where there is a recent [PR#7](https://github.com/SteveSanderson/Blazor/pull/7/files#diff-ca0de2f90d92a625eeb26c72f0fd0bb4R1599)  to make tailcalls at least not crash the interpreter :)

**Comment by ncave** [comment]
@dsyme @chrisdunelm
I added some tail calls optimizations in a downstream [repo](https://github.com/ncave/dotnet-js/commit/010aaee6e16b4c704d1cffbc1836cb9b07941b75), and also in the Blazor [PR#7](https://github.com/SteveSanderson/Blazor/pull/7) that adds F# support. (Sorry for resurrecting this issue, I'll show myself out.)
